blog_main_post:
    path:    /post/{id}
    defaults: { _controller: BlogMainBundle:Post:post }

blog_main_genre:
    path:    /genre/{id}
    defaults: { _controller: BlogMainBundle:Post:genre }

blog_main_post_sidebar:
    path:   /sidebar/{post}
    defaults: { _controller: BlogMainBundle:Post:sidebar, post : null }