blog_main_post:
    path:    /post/{id}/{page}
    defaults: { _controller: BlogMainBundle:Post:post, page : 1 }

blog_main_genre:
    path:    /genre/{id}
    defaults: { _controller: BlogMainBundle:Post:genre }

blog_main_post_sidebar:
    path:   /sidebar/{post}
    defaults: { _controller: BlogMainBundle:Post:sidebar, post : null }

blog_main_post_redirect:
    path:   /r/{url}
    defaults: { _controller: BlogMainBundle:Post:redirect, url: null }
    methods: [ GET, POST, PUT ]
    requirements:
        url:    .*
