blog_main_post:
    resource: "@BlogMainBundle/Resources/config/routing/post.yml"
    prefix:   /settings

blog_main_homepage:
    path:     /{page}
    defaults: { _controller: BlogMainBundle:Default:index, page: 1 }
    requirements:
        page: \d+

blog_main_archives:
    path:   /archive/{date}
    defaults: { _controller: BlogMainBundle:Archives:index }
    requirements:
        _method: GET

blog_main_about:
    path:   /about
    defaults: { _controller: BlogMainBundle:Default:about }

blog_main_social_links:
    path:   /socialLinks
    defaults: { _controller: BlogMainBundle:Default:socialLinks }
